// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sophonzotlphttp")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/sophonzotlphttpexporter"
)

const (
	TracesStability  = component.StabilityLevelStable
	MetricsStability = component.StabilityLevelStable
	LogsStability    = component.StabilityLevelStable
)
