// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("sophonzconsoleprint")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/sophonzconsoleprintprocessor"
)

const (
	TracesStability = component.StabilityLevelStable
	LogsStability   = component.StabilityLevelBeta
)
