DROP TABLE IF EXISTS sophonz_traces.stored_dashboard_metrics_1m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_dashboard_metrics_5m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_dashboard_metrics_1h ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_dashboard_metrics_1d ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_session_1m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_session_5m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_session_1h ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_session_1d ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_screen_loading_time_1m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_screen_loading_time_5m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_screen_loading_time_1h ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_screen_loading_time_1d ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_http_request_response_time_1m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_http_request_response_time_5m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_http_request_response_time_1h ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_http_request_response_time_1d ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_user_resource_summary_1m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_user_resource_summary_5m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_user_resource_summary_1h ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_analysis_user_resource_summary_1d ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_data_traces_1m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_data_traces_5m ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_data_traces_1h ON CLUSTER {{.SOPHONZ_CLUSTER}};
DROP TABLE IF EXISTS sophonz_traces.stored_data_traces_1d ON CLUSTER {{.SOPHONZ_CLUSTER}};

DROP VIEW IF EXISTS sophonz_traces.mv_dashboard_metrics_1m;
DROP VIEW IF EXISTS sophonz_traces.mv_dashboard_metrics_5m;
DROP VIEW IF EXISTS sophonz_traces.mv_dashboard_metrics_1h;
DROP VIEW IF EXISTS sophonz_traces.mv_dashboard_metrics_1d;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_session_1m;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_session_5m;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_session_1h;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_session_1d;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_screen_loading_time_1m;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_screen_loading_time_5m;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_screen_loading_time_1h;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_screen_loading_time_1d;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_http_request_response_time_1m;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_http_request_response_time_5m;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_http_request_response_time_1h;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_http_request_response_time_1d;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_user_resource_summary_1m;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_user_resource_summary_5m;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_user_resource_summary_1h;
DROP VIEW IF EXISTS sophonz_traces.mv_analysis_user_resource_summary_1d;
DROP VIEW IF EXISTS sophonz_traces.mv_data_traces_1m;
DROP VIEW IF EXISTS sophonz_traces.mv_data_traces_5m;
DROP VIEW IF EXISTS sophonz_traces.mv_data_traces_1h;
DROP VIEW IF EXISTS sophonz_traces.mv_data_traces_1d;
